import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

const glossaryCsvPath = path.join(repoRoot, "language-packs/base/glossary_seed.csv");
const doNotTranslateCsvPath = path.join(
  repoRoot,
  "language-packs/base/do_not_translate_seed.csv"
);
const outputPath = path.join(repoRoot, "utils/generatedTerminology.ts");

const parseCsv = (raw) => {
  const rows = [];
  let current = [];
  let field = "";
  let inQuotes = false;

  for (let i = 0; i < raw.length; i += 1) {
    const char = raw[i];
    const next = raw[i + 1];

    if (inQuotes) {
      if (char === '"' && next === '"') {
        field += '"';
        i += 1;
      } else if (char === '"') {
        inQuotes = false;
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') {
      inQuotes = true;
      continue;
    }

    if (char === ",") {
      current.push(field);
      field = "";
      continue;
    }

    if (char === "\n") {
      current.push(field);
      rows.push(current);
      current = [];
      field = "";
      continue;
    }

    if (char === "\r") {
      continue;
    }

    field += char;
  }

  if (field.length > 0 || current.length > 0) {
    current.push(field);
    rows.push(current);
  }

  return rows.filter((row) => row.some((cell) => String(cell || "").trim()));
};

const readCsvObjects = (filePath) => {
  const raw = fs.readFileSync(filePath, "utf8");
  const rows = parseCsv(raw);
  if (rows.length === 0) return [];
  const headers = rows[0].map((header) => String(header || "").trim());
  return rows.slice(1).map((row) => {
    const record = {};
    headers.forEach((header, index) => {
      record[header] = String(row[index] || "").trim();
    });
    return record;
  });
};

const glossaryRows = readCsvObjects(glossaryCsvPath);
const doNotTranslateRows = readCsvObjects(doNotTranslateCsvPath);

const content = `/* eslint-disable */
// Auto-generated by scripts/generateTerminologyAssets.mjs. Do not edit by hand.

export interface GeneratedGlossarySeedRow {
  term_id: string;
  domain: string;
  term_type: string;
  zh_source: string;
  en_draft: string;
  es_draft: string;
  fr_draft: string;
  de_draft: string;
  it_draft: string;
  pt_draft: string;
  ru_draft: string;
  tr_draft: string;
  source_files: string;
  status: string;
  notes: string;
}

export interface GeneratedDoNotTranslateSeedRow {
  lock_id: string;
  source_text: string;
  category: string;
  match_type: string;
  scope: string;
  reason: string;
  source_files: string;
  notes: string;
}

export const GENERATED_GLOSSARY_SEED: GeneratedGlossarySeedRow[] = ${JSON.stringify(
  glossaryRows,
  null,
  2
)};

export const GENERATED_DO_NOT_TRANSLATE_SEED: GeneratedDoNotTranslateSeedRow[] = ${JSON.stringify(
  doNotTranslateRows,
  null,
  2
)};
`;

fs.writeFileSync(outputPath, content);

console.log(
  `Generated terminology assets: ${glossaryRows.length} glossary rows, ${doNotTranslateRows.length} protected terms.`
);
